# Generated by Django 3.2.7 on 2021-10-15 15:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import apps.portfolio.models_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                ("name", models.CharField(max_length=125, primary_key=True, serialize=False)),
                ("url", models.URLField()),
                ("icon", models.ImageField(upload_to=apps.portfolio.models_utils.get_encoded_file_name)),
            ],
        ),
        migrations.CreateModel(
            name="BrandType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(choices=[("SOCIAL", "Social Media"), ("TECH", "Technology")], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name="BulletGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                ("column", models.PositiveIntegerField(choices=[(0, "LEFT"), (1, "RIGHT")])),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=127)),
                ("short_description", models.TextField()),
                ("description", models.TextField()),
                ("code_url", models.URLField(blank=True, null=True)),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to=apps.portfolio.models_utils.get_encoded_file_name
                    ),
                ),
                (
                    "technologies",
                    models.ManyToManyField(
                        limit_choices_to={"brand_type__name": "TECH"}, related_name="projects", to="portfolio.Brand"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WebsiteSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("main_title", models.CharField(max_length=128)),
                ("sub_title", models.CharField(blank=True, max_length=256, null=True)),
                ("summary", models.CharField(blank=True, max_length=512, null=True)),
                ("first_name", models.CharField(max_length=128)),
                ("last_name", models.CharField(blank=True, max_length=128, null=True)),
                ("email", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "theme_color",
                    models.CharField(
                        default="25639e", max_length=6, validators=[django.core.validators.MaxLengthValidator(6)]
                    ),
                ),
                ("avatar", models.ImageField(blank=True, null=True, upload_to="")),
                ("logo", models.ImageField(blank=True, null=True, upload_to="")),
            ],
            options={
                "verbose_name": "website settings",
                "verbose_name_plural": "website settings",
            },
        ),
        migrations.CreateModel(
            name="ProjectTechnology",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="portfolio.project")),
                ("technology", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="portfolio.brand")),
            ],
            options={
                "verbose_name": "Project technology",
                "verbose_name_plural": "Project technologies",
            },
        ),
        migrations.CreateModel(
            name="ProjectImages",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="images", to="portfolio.project"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MyBullet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="bullets", to="portfolio.bulletgroup"
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="brand",
            name="brand_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="brands", to="portfolio.brandtype"
            ),
        ),
    ]
