# Generated by Django 3.2.7 on 2021-09-23 09:54

import apps.portfolio.models_utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulletGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('column', models.PositiveIntegerField(choices=[(0, 'LEFT'), (1, 'RIGHT')])),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('description', models.TextField()),
                ('code_url', models.URLField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=apps.portfolio.models_utils.get_encoded_file_name)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('name', models.CharField(max_length=125, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('icon', models.ImageField(upload_to=apps.portfolio.models_utils.get_encoded_file_name)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar', models.ImageField(upload_to=apps.portfolio.models_utils.get_encoded_file_name)),
                ('summary', models.TextField()),
                ('logo', models.ImageField(upload_to='', default="")),
                ('first_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MyBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullets', to='portfolio.bulletgroup')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('header', models.CharField(blank=True, max_length=511, null=True)),
                ('text_body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.portfolio.models_utils.get_encoded_file_name)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='portfolio.project')),
            ],
            options={
                'unique_together': {('project', 'number')},
            },
        ),
    ]
