# Generated by Django 3.2.7 on 2021-09-15 10:26

import django.db.models.deletion
from django.db import migrations, models

import apps.portfolio.models_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=127)),
                ("description", models.TextField()),
                ("url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="ProjectPageSection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.PositiveIntegerField()),
                ("header", models.CharField(max_length=511)),
                ("text_body", models.TextField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sections", to="portfolio.project"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SectionMedia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to=apps.portfolio.models_utils.get_encoded_file_name)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="portfolio.projectpagesection",
                    ),
                ),
            ],
        ),
    ]
