# Generated by Django 3.2.7 on 2021-09-23 17:54

import apps.portfolio.models_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel('WebsiteSettings', 'PortfolioInfo'),
        migrations.RemoveField(
            model_name='portfolioinfo',
            name='logo',
        ),
    ]
