# Generated by Django 3.2.7 on 2021-09-15 14:00

import apps.portfolio.models_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210915_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='code_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=apps.portfolio.models_utils.get_encoded_file_name),
        ),
    ]
