# Generated by Django 3.2.7 on 2021-09-27 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_auto_20210923_1954"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectImages",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
        migrations.RenameField(model_name="project", old_name="description", new_name="short_description"),
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="ProjectPageSection",
        ),
        migrations.AddField(
            model_name="projectimages",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="images", to="portfolio.project"
            ),
        ),
    ]
