# Generated by Django 3.2.7 on 2021-09-16 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20210915_1600'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectpagesection',
            unique_together={('project', 'number')},
        ),
    ]
