# Generated by Django 3.2.7 on 2021-09-27 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20210927_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=128)),
                ('sub_title', models.CharField(blank=True, max_length=256, null=True)),
                ('summary', models.CharField(blank=True, max_length=512, null=True)),
                ('first_name', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.CharField(blank=True, max_length=128, null=True)),
                ('theme_color', models.CharField(default='25639e', max_length=6, validators=[django.core.validators.MaxLengthValidator(6)])),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'website settings',
                'verbose_name_plural': 'website settings',
            },
        ),
        migrations.DeleteModel(
            name='PortfolioInfo',
        ),
    ]
