# Generated by Django 3.2.7 on 2021-09-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20210927_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='last_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='first_name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
