# Generated by Django 3.2.7 on 2021-09-16 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_projectpagesection_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionmedia',
            name='section',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='portfolio.projectpagesection'),
        ),
    ]
