# Generated by Django 3.2.7 on 2021-09-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20210927_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='document_title',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
