# Generated by Django 3.2.7 on 2021-09-16 09:02

import apps.portfolio.models_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_sectionmedia_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpagesection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.portfolio.models_utils.get_encoded_file_name),
        ),
        migrations.DeleteModel(
            name='SectionMedia',
        ),
    ]
