# Generated by Django 3.2.7 on 2021-09-27 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_websitesettings_document_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitesettings',
            name='document_title',
        ),
    ]
