# Generated by Django 3.2.7 on 2021-09-17 11:41

import apps.portfolio.models_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20210916_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('name', models.CharField(max_length=125, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('icon', models.ImageField(upload_to=apps.portfolio.models_utils.get_encoded_file_name)),
            ],
        ),
    ]
