# Generated by Django 3.2.7 on 2021-09-29 12:23

import apps.portfolio.models_utils
from django.db import migrations, models
import django.db.models.deletion


def insert_brand_types(apps, schema_editor) -> None:
    BrandType = apps.get_model("portfolio", "BrandType")
    BrandType.objects.using(schema_editor.connection.alias).bulk_create(
        [
            BrandType(name="SOCIAL"),
            BrandType(name="TECH"),
        ]
    )


def remove_brand_types(apps, schema_editor) -> None:
    BrandType = apps.get_model("portfolio", "BrandType")
    BrandType.objects.using(schema_editor.connection.alias).delete()


def link_with_brand_type(apps, schema_editor) -> None:
    BrandType = apps.get_model("portfolio", "BrandType")
    Brand = apps.get_model("portfolio", "Brand")
    db_alias = schema_editor.connection.alias
    social_media_type = BrandType.objects.using(db_alias).get(name="SOCIAL")
    Brand.objects.using(db_alias).update(brand_type=social_media_type)

class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_remove_websitesettings_document_title"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SocialMedia",
            new_name="Brand",
        ),
        migrations.CreateModel(
            name="BrandType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(choices=[("SOCIAL", "Social Media"), ("TECH", "Technology")], max_length=16)),
            ],
        ),
        migrations.RunPython(insert_brand_types, remove_brand_types),
        migrations.AddField(
            model_name="brand",
            name="brand_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brands",
                to="portfolio.brandtype",
                null=True,
            ),
        ),
        migrations.RunPython(link_with_brand_type),
        migrations.AlterField(
            model_name="brand",
            name="brand_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brands",
                to="portfolio.brandtype",
                null=False,
            ),
        )
    ]
