# Generated by Django 3.2.7 on 2021-09-29 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_projecttechnology'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecttechnology',
            options={'verbose_name': 'Project technology', 'verbose_name_plural': 'Project technologies'},
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(related_name='projects', through='portfolio.ProjectTechnology', to='portfolio.Brand'),
        ),
        migrations.AlterField(
            model_name='projecttechnology',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.project'),
        ),
        migrations.AlterField(
            model_name='projecttechnology',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.brand'),
        ),
    ]
